version: '3'

services:
  factorio_server:
    image: factorio:1.1.69
    ports:
      - "34197:34197/udp"
    restart: unless-stopped
    volumes:
      - type: bind
        source: ./server-settings.json
        target: /usr/local/factorio/data/server-settings.json
      - type: bind
        source: ./saves
        target: /usr/local/factorio/saves