version: '3'

services:
  factorio_server:
    build: .
    ports:
      - "24197:24197/udp"
      - "27015:27015/tcp"
    restart: unless-stopped
    volumes:
      - factorio:/factorio
    environment:
      # - GENERATE_NEW_SAVE=True
      - NAME=BunkerFactorio0
      - LOAD_LATEST_SAVE=False
      - SAVE_NAME=world
      - GAME_PASSWORD=rage01
    # entrypoint: "tail -f /dev/null"
volumes:
  factorio: