version: '3'

services:
  factorio_server:
    build: .
    ports:
      - "24197:24197/udp"
      - "27015:27015/tcp"
    restart: unless-stopped
    volumes:
      - factorio:/factorio
    environment:
      - GENERATE_NEW_SAVE=true
    #   - DEBUG=true
    # entrypoint: "tail -f /dev/null"
volumes:
  factorio: